version: 2.1

executors:
  test-bundle:
    docker:
      - image: cimg/base:2021.04
        environment:
          FOO: $foo
        command: ["sh", "-c", "env"]

      # - image: alpine
      #   environment:
      #     FOO: $foo
      #   command: ["sh", "-c", "env"]

jobs:
  build:
    docker:
      - image: alpine
    environment:
      FOO: $foo
    steps:
      - run: sh -c env
  bundle:
    executor: test-bundle
    steps:
      - run: sh -c env

workflows:
  test:
    jobs:
      - build
      - bundle
